[build]
  command = "bun install --legacy-peer-deps && bun run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "https://cpmc-back-production.up.railway.app"
  VITE_NODE_ENV = "production"